language: python
python:
    - '3.8'
    - '3.7'
    - '3.6'
install:
    - pip install -r requirements.txt
script:
    - pytest --cov=./
after_success:
    - bash <(curl -s https://codecov.io/bash)

